CREATE TABLE "PRUBSNCOMM"."MAP_CHANNEL_CATEGORY" ("MAP_ID" NUMBER(8,0) NOT NULL, "CATEGORYID" NUMBER(8,0), "CHANNELID" NUMBER(8,0), "USERNAME" VARCHAR2(255 BYTE)   ); 
  
CREATE SEQUENCE  "PRUBSNCOMM"."MAP_CHANNEL_CATEGORY_SEQ"  MINVALUE 1 MAXVALUE 99999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER  NOCYCLE ;

ALTER TABLE MESSAGE ADD REFERENCE_NO VARCHAR2(100);

ALTER TABLE "PRUBSNCOMM"."CATEGORY" ADD SETCATEGORYID NUMBER(10,0); 
ALTER TABLE "PRUBSNCOMM"."CATEGORY" ADD SETCATEGORYNAME VARCHAR2(255 CHAR);
ALTER TABLE "PRUBSNCOMM"."CATEGORY" ADD CATESTATUS VARCHAR2(255 CHAR); 
ALTER TABLE "PRUBSNCOMM"."CATEGORY" ADD CATEGORYNAMEBHASA1 VARCHAR2(255 CHAR);
ALTER TABLE "PRUBSNCOMM"."CATEGORY" ADD CATEGORYNAMEBHASA VARCHAR2(255 CHAR);
ALTER TABLE "PRUBSNCOMM"."CATEGORY" ADD ACTION VARCHAR2(255 BYTE);
ALTER TABLE "PRUBSNCOMM"."CATEGORY" ADD USERNAME VARCHAR2(255 CHAR);

ALTER TABLE "PRUBSNCOMM"."CHANNEL" ADD ISAPPROVED VARCHAR2(255 CHAR); 
ALTER TABLE "PRUBSNCOMM"."CHANNEL" ADD ACTION VARCHAR2(255 BYTE); 
ALTER TABLE "PRUBSNCOMM"."CHANNEL" ADD USERNAME VARCHAR2(255 CHAR);

ALTER TABLE "PRUBSNCOMM"."MESSAGE_DETAILS" ADD USERNAME VARCHAR2(255 BYTE);

ALTER TABLE "PRUBSNCOMM"."USER_CHANNEL" ADD CHANNELCODE VARCHAR2(255 BYTE);