package com.company.crm.exception;

/**
 * This class contains GenericException data.
 *
 * @author dinesh
 */
public class GenericException extends Exception {

    /**
     * Autogenerated Id
     */
    public static final long serialVersionUID = -1;

    /**
     * Error text
     */
    private String errorText;
    /**
     * Error context
     */
    private String errorContext;

    /**
     * Error code
     */
    private String errorCode;

    /**
     * Constructor
     * @param e Exception
     */
    public GenericException(Exception e) {
    	super(e);
    	this.errorText = e.getMessage();
    }
    /**
     * Constructor
     *
     * @param errorContext String
     * @param errorCode String
     * @param errorText
     */
    public GenericException(String errorContext, String errorCode,
                               String errorText) {
    	super(errorText);
    	this.errorText = errorText;
        this.errorContext = errorContext;
        this.errorCode = errorCode;
    }

    /**
     * Constructor
     *
     * @param errorContext String
     * @param errorCode String
     * @param errorText String
     * @param cause Throwable
     */
    public GenericException(String errorContext, String errorCode,
                               String errorText, Throwable cause) {
        super(errorText, cause);
        this.errorText = errorText;
        this.errorContext = errorContext;
        this.errorCode = errorCode;
    }

	/**
	 * Returns error context
	 *
	 * @return errorContext String
	 */
	public String getErrorContext() {
		return errorContext;
	}

	/**
	 * Sets error context
	 *
	 * @param errorContext String
	 */
	public void setErrorContext(String errorContext) {
		this.errorContext = errorContext;
	}

	/**
	 * Returns the error code.
	 *
	 * @return errorCode String
	 */
	public String getErrorCode() {
		return errorCode;
	}

	/**
	 * Sets the error code.
	 *
	 * @param errorCode String
	 */
	public void setErrorCode(String errorCode) {
		this.errorCode = errorCode;
	}
	/**
	 * returns Error Text
	 * @return errorText
	 */
	public String getErrorText() {
		return errorText;
	}
	/**
	 * sets Error Text
	 * @param errorText String
	 */
	public void setErrorText(String errorText) {
		this.errorText = errorText;
	}



}

